// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlrIQsDTaOEUDZyNC78i3fXqj7eXUXHRM',
    appId: '1:246470871216:web:1373cbe543e56c80e41375',
    messagingSenderId: '246470871216',
    projectId: 'flutter-e-commerce-6eaf4',
    authDomain: 'flutter-e-commerce-6eaf4.firebaseapp.com',
    storageBucket: 'flutter-e-commerce-6eaf4.appspot.com',
    measurementId: 'G-TKBJXBZLB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8rOAMaL_x5J8FYbdCMOBbFxlloQir9t8',
    appId: '1:246470871216:android:cae35d72c14f4e42e41375',
    messagingSenderId: '246470871216',
    projectId: 'flutter-e-commerce-6eaf4',
    storageBucket: 'flutter-e-commerce-6eaf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDekUdfHULByw8qNZV3wBqPNOBZ4sWJxWk',
    appId: '1:246470871216:ios:13f706ebeeaebc16e41375',
    messagingSenderId: '246470871216',
    projectId: 'flutter-e-commerce-6eaf4',
    storageBucket: 'flutter-e-commerce-6eaf4.appspot.com',
    iosBundleId: 'com.example.flutterECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDekUdfHULByw8qNZV3wBqPNOBZ4sWJxWk',
    appId: '1:246470871216:ios:13f706ebeeaebc16e41375',
    messagingSenderId: '246470871216',
    projectId: 'flutter-e-commerce-6eaf4',
    storageBucket: 'flutter-e-commerce-6eaf4.appspot.com',
    iosBundleId: 'com.example.flutterECommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlrIQsDTaOEUDZyNC78i3fXqj7eXUXHRM',
    appId: '1:246470871216:web:5146aa649fb4db78e41375',
    messagingSenderId: '246470871216',
    projectId: 'flutter-e-commerce-6eaf4',
    authDomain: 'flutter-e-commerce-6eaf4.firebaseapp.com',
    storageBucket: 'flutter-e-commerce-6eaf4.appspot.com',
    measurementId: 'G-R1XN5GME5H',
  );
}
